import math
import pathlib
import re
import subprocess

import pytest

from drivebase_behaviour.ik import JOINT_LIMITS, solve
from drivebase_behaviour.kinematics import (
    extract_planar_arm,
    forward_kinematics,
    load_chain,
)

REPO = pathlib.Path(__file__).resolve().parents[3]


@pytest.fixture(scope="module")
def urdf_xml():
    xacro = REPO / "src/drivebase_description/urdf/drivebase.urdf.xacro"
    return subprocess.run(
        ["xacro", str(xacro), "use_sim:=true", "use_arm:=true",
         "wheel_mu1:=1.0", "wheel_mu2:=0.6"],
        capture_output=True, text=True, check=True,
    ).stdout


@pytest.fixture(scope="module")
def chain(urdf_xml):
    return load_chain(urdf_xml, "arm_base_link", "arm_gripper_frame_link")


@pytest.fixture(scope="module")
def wrist_chain(urdf_xml):
    """Stops at the wrist_flex joint's child, so its translation is where the
    last link starts. Rotating wrist_flex does not move that point."""
    return load_chain(urdf_xml, "arm_base_link", "arm_wrist_link")


@pytest.fixture(scope="module")
def arm(chain):
    return extract_planar_arm(chain)


def joints(solution):
    return {
        "arm_shoulder_pan": solution.shoulder_pan,
        "arm_shoulder_lift": solution.shoulder_lift,
        "arm_elbow_flex": solution.elbow_flex,
        "arm_wrist_flex": solution.wrist_flex,
    }


def reachable_targets(arm):
    """Planar (r, z, approach) triples generated by the planar model itself,
    so they are reachable by construction.

    The angles here are *planar* angles, not joint commands - the model is
    written in those, and `arm.sense` is what converts. Feeding joint values in
    here would still produce reachable points, just not the ones named.
    """
    out = []
    for q1, q2, q3 in [(0.2, -0.3, 0.1), (-0.3, 0.5, -0.2), (0.6, -0.8, 0.4)]:
        r = arm.origin_r + (
            arm.l1 * math.cos(arm.a1 + q1)
            + arm.l2 * math.cos(arm.a2 + q1 + q2)
            + arm.l3 * math.cos(arm.a3 + q1 + q2 + q3))
        z = arm.origin_z + (
            arm.l1 * math.sin(arm.a1 + q1)
            + arm.l2 * math.sin(arm.a2 + q1 + q2)
            + arm.l3 * math.sin(arm.a3 + q1 + q2 + q3))
        out.append((r, z, arm.a3 + q1 + q2 + q3))
    return out


def test_joint_limits_still_match_the_urdf(urdf_xml):
    """The table is hardcoded so Task 11's driver can import it without
    parsing a URDF. This is the guard that keeps it honest."""
    for name, (low, high) in JOINT_LIMITS.items():
        match = re.search(
            rf'<joint name="arm_{name}" type="revolute">.*?'
            r'<limit[^>]*lower="([-\d.]+)"\s+upper="([-\d.]+)"',
            urdf_xml, re.DOTALL)
        assert match, name
        assert float(match.group(1)) == pytest.approx(low)
        assert float(match.group(2)) == pytest.approx(high)


def test_solution_round_trips_through_forward_kinematics(chain, arm):
    """The only IK test that proves anything: solve, then FK the answer back
    and assert it lands on the commanded point.

    Targets are built with `from_planar`, which is the inverse of the
    projection `solve` uses. Constructing them as `(r*cos(pan), r*sin(pan), z)`
    instead - measuring the radius from the base origin rather than the pan
    axis 38.8 mm away - names a point the arm cannot reach at that bearing,
    and asserts against a pan the solver has no reason to return.
    """
    for r, z, approach in reachable_targets(arm):
        for pan in (0.0, 0.4, -0.7):
            target = arm.from_planar(r, z, pan)
            s = solve(arm, target, approach, JOINT_LIMITS)
            assert s is not None, (target, approach)

            tip = forward_kinematics(chain, joints(s))[:3, 3]
            # 1e-5, not 1e-9: the CAD export writes pi as 3.14159, which tilts
            # the pan axis 2.65e-6 rad off vertical. Task 9's tolerance, and
            # for the same reason.
            assert tip[0] == pytest.approx(target[0], abs=1e-5)
            assert tip[1] == pytest.approx(target[1], abs=1e-5)
            assert tip[2] == pytest.approx(target[2], abs=1e-5)


def test_the_last_link_arrives_at_the_commanded_approach_angle(
        chain, wrist_chain, arm):
    """Position alone does not pin the wrist: a wrong q3 still lands the tip
    on target with the gripper pointing somewhere else, which is how you close
    the jaws sideways onto litter."""
    for r, z, approach in reachable_targets(arm):
        s = solve(arm, arm.from_planar(r, z, 0.3), approach, JOINT_LIMITS)
        assert s is not None

        tip = forward_kinematics(chain, joints(s))[:3, 3]
        wrist = forward_kinematics(wrist_chain, joints(s))[:3, 3]
        tip_r, tip_z = arm.to_planar(tip, s.shoulder_pan)
        wrist_r, wrist_z = arm.to_planar(wrist, s.shoulder_pan)

        achieved = math.atan2(tip_z - wrist_z, tip_r - wrist_r)
        assert achieved == pytest.approx(approach, abs=1e-4)


def test_returns_none_when_the_point_is_out_of_reach(arm):
    far = arm.from_planar(
        arm.origin_r + arm.l1 + arm.l2 + arm.l3 + 0.5, arm.origin_z, 0.0)
    assert solve(arm, far, -math.pi / 2, JOINT_LIMITS) is None


def test_returns_none_inside_the_dead_zone_around_the_shoulder(arm):
    """The 2R stage has an inner bound as well as an outer one: with unequal
    links the wrist cannot come closer to the shoulder than |l1 - l2|, which
    is 19 mm here. A naive solve takes acos of something past 1 and raises a
    domain error rather than reporting the point unreachable."""
    gap = abs(arm.l1 - arm.l2) / 2.0
    target = arm.from_planar(
        arm.origin_r + arm.l3 + gap, arm.origin_z, 0.0)
    assert solve(arm, target, 0.0, JOINT_LIMITS) is None


def test_every_returned_joint_is_inside_its_limit(arm):
    for r, z, approach in reachable_targets(arm):
        s = solve(arm, arm.from_planar(r, z, 0.0), approach, JOINT_LIMITS)
        if s is None:
            continue
        for name, value in [
            ("shoulder_pan", s.shoulder_pan),
            ("shoulder_lift", s.shoulder_lift),
            ("elbow_flex", s.elbow_flex),
            ("wrist_flex", s.wrist_flex),
        ]:
            lo, hi = JOINT_LIMITS[name]
            assert lo <= value <= hi, (name, value)


def test_returns_none_when_the_solution_violates_a_limit(arm):
    # Squeeze shoulder_pan to a hair either side of zero: a target off to the
    # side then has no legal pan, so the solver must refuse rather than
    # silently clamp and aim somewhere else.
    tight = dict(JOINT_LIMITS)
    tight["shoulder_pan"] = (-0.01, 0.01)
    r, z, approach = reachable_targets(arm)[0]
    target = arm.from_planar(r, z, 1.2)
    assert solve(arm, target, approach, tight) is None


def test_refuses_rather_than_clamps_when_only_a_pitch_joint_is_blocked(arm):
    """The pan check is the easy one - it happens before any geometry. This
    pins the check at the far end, after both elbow branches."""
    tight = dict(JOINT_LIMITS)
    tight["wrist_flex"] = (-0.001, 0.001)
    r, z, approach = reachable_targets(arm)[0]
    assert solve(arm, arm.from_planar(r, z, 0.0), approach, tight) is None


def test_pan_points_at_the_target_bearing(arm):
    r, z, approach = reachable_targets(arm)[0]
    for pan in (0.5, -0.9):
        s = solve(arm, arm.from_planar(r, z, pan), approach, JOINT_LIMITS)
        assert s is not None
        assert s.shoulder_pan == pytest.approx(pan, abs=1e-9)


# Gripper height at the lowest measured pose, minus the mount height, both
# from PROGRESS.md's workspace table. In `arm_base_link`, whose origin is the
# mount, that is where litter sits.
GRASP_Z = 0.0354 - 0.260


def test_a_vertical_approach_solves_at_the_measured_grasp_height(arm):
    """The case the whole module exists to serve: the gripper comes straight
    down onto litter on the ground.

    THE RADIUS HERE IS IN THE ARM'S PLANAR FRAME, measured from the pan axis -
    not the 287-481 mm grasp window in PROGRESS.md, which is `base_footprint`
    x and sits 254 mm further out (the arm is mounted on the front face at
    x = 0.215, and the pan axis is 38.8 mm ahead of `arm_base_link`). Reading
    those robot-frame numbers as radii asks for a point 25 cm past the arm's
    reach, and gets a truthful None.
    """
    for radius in (0.13, 0.14, 0.145):
        s = solve(arm, arm.from_planar(radius, GRASP_Z, 0.0),
                  -math.pi / 2, JOINT_LIMITS)
        assert s is not None, radius


def test_the_grasp_height_band_is_narrow_and_the_approach_is_forced(arm):
    """Not a requirement - a measurement, pinned so it cannot drift unnoticed.

    At grasp height the arm is within a millimetre of full extension, so the
    reachable band is only ~50 mm wide radially and the approach angle is
    forced to within a few degrees of vertical. The grasp sequence therefore
    has no freedom to pick an approach down there, and the base must be
    positioned in that band rather than anywhere in the workspace. If this
    test starts failing the arm geometry changed, and Task 12's descent
    assumptions need re-deriving with it.
    """
    reachable = [
        r / 1000 for r in range(80, 300)
        if solve(arm, arm.from_planar(r / 1000, GRASP_Z, 0.0),
                 -math.pi / 2, JOINT_LIMITS) is not None
    ]
    assert reachable, "nothing reaches grasp height at all"
    assert max(reachable) - min(reachable) < 0.08

    widest = max(reachable)
    angles = [
        d for d in range(-90, 91)
        if solve(arm, arm.from_planar(widest, GRASP_Z, 0.0),
                 math.radians(d), JOINT_LIMITS) is not None
    ]
    assert angles and min(angles) <= -85 and max(angles) <= -80
